import { QuizQuestion } from '@/lib/types'

// ──────────────────────────────────────────
// Chapter 1–6  (기초 문법)
// ──────────────────────────────────────────
const chapter1to6: QuizQuestion[] = [
  {
    id: 'cl1-c2-q1',
    chapter: 2,
    question: 'C 언어에서 정수형 변수를 선언하는 올바른 방법은?',
    options: ['integer x;', 'int x;', 'Int x;', 'var x: int;'],
    correctIndex: 1,
    explanation: 'C 언어에서 정수형 변수는 int 키워드로 선언합니다. integer, Int, var 는 C 문법에 존재하지 않습니다.',
  },
  {
    id: 'cl1-c3-q1',
    chapter: 3,
    question: 'C 언어에서 표준 출력에 사용하는 함수는?',
    options: ['print()', 'echo()', 'printf()', 'System.out.println()'],
    correctIndex: 2,
    explanation: 'printf() 는 C 언어의 표준 출력 함수로, <stdio.h> 헤더에 정의되어 있습니다.',
  },
  {
    id: 'cl1-c5-q1',
    chapter: 5,
    question: '다음 중 C 언어의 기본 반복문이 아닌 것은?',
    options: ['for', 'while', 'foreach', 'do-while'],
    correctIndex: 2,
    explanation: 'foreach 는 C 언어에 존재하지 않습니다. C 언어는 for, while, do-while 세 가지 반복문을 제공합니다.',
  },
  {
    id: 'cl1-c6-q1',
    chapter: 6,
    question: 'C 언어에서 포인터 변수를 선언할 때 사용하는 기호는?',
    options: ['&', '*', '#', '@'],
    correctIndex: 1,
    explanation: '* 를 사용하여 포인터 변수를 선언합니다. 예: int *ptr; / & 는 변수의 주소를 얻는 연산자입니다.',
  },
  {
    id: 'cl1-c4-q1',
    chapter: 4,
    question: '다음 C 코드의 출력 결과는?  printf("%d", 3 + 4 * 2);',
    options: ['14', '11', '10', '8'],
    correctIndex: 1,
    explanation: '연산자 우선순위에 따라 4 * 2 = 8 이 먼저 계산되고, 3 + 8 = 11 이 출력됩니다.',
  },
]

// ──────────────────────────────────────────
// Chapter 7  — 배열 (Array)
// ──────────────────────────────────────────
const chapter7: QuizQuestion[] = [
  {
    id: 'cl1-c7-q1',
    chapter: 7,
    question: '다음 중 C 언어 배열(array)에 대한 설명으로 옳지 않은 것은?',
    options: [
      '배열의 인덱스는 0부터 시작한다.',
      '배열은 서로 다른 데이터형의 원소를 함께 저장할 수 있다.',
      '배열의 각 원소는 메모리에 연속적으로 할당된다.',
      '배열의 각 원소도 변수처럼 값을 읽고 쓸 수 있다.',
    ],
    correctIndex: 1,
    explanation: '배열은 같은 데이터형의 원소만 저장할 수 있습니다. 서로 다른 데이터형을 묶으려면 구조체(struct)를 사용합니다.',
  },
  {
    id: 'cl1-c7-q2',
    chapter: 7,
    question: '다음 선언이 있을 때, sizeof(arr) / sizeof(arr[0])의 값은?',
    codeBlock: 'int arr[10];',
    options: ['4', '5', '10', '40'],
    correctIndex: 2,
    explanation: 'sizeof(arr) = 4 × 10 = 40바이트, sizeof(arr[0]) = 4바이트이므로 40 / 4 = 10 (배열의 원소 개수)입니다.',
  },
  {
    id: 'cl1-c7-q3',
    chapter: 7,
    question: '다음 코드에서 배열 초기화에 대한 설명으로 옳지 않은 것은?',
    codeBlock: 'int arr[5] = {1, 2, 3};',
    options: [
      'arr[0]의 값은 1이다.',
      'arr[3]과 arr[4]는 0으로 초기화된다.',
      '초기값을 6개 이상 지정하면 컴파일 에러가 발생한다.',
      'arr[2]의 값은 0이다.',
    ],
    correctIndex: 3,
    explanation: 'arr[2]는 세 번째 초기값인 3입니다. 초기값이 부족한 arr[3], arr[4]만 0으로 자동 초기화됩니다.',
  },
  {
    id: 'cl1-c7-q4',
    chapter: 7,
    question: '다음과 같이 배열을 선언했을 때, 유효한 인덱스 범위로 옳은 것은?',
    codeBlock: 'int data[8];',
    options: ['1 ~ 8', '0 ~ 7', '0 ~ 8', '1 ~ 7'],
    correctIndex: 1,
    explanation: 'C 배열의 인덱스는 0부터 시작합니다. data[0] ~ data[7]이 유효하며, data[8]은 배열 범위 초과(out-of-bounds)로 미정의 동작을 일으킵니다.',
  },
  {
    id: 'cl1-c7-q5',
    chapter: 7,
    question: 'int table[3][4]; 로 선언된 2차원 배열의 전체 원소 개수는?',
    options: ['3', '4', '7', '12'],
    correctIndex: 3,
    explanation: '2차원 배열의 원소 개수 = 행 크기 × 열 크기 = 3 × 4 = 12',
  },
  {
    id: 'cl1-c7-q6',
    chapter: 7,
    question: '다음 중 int arr[5]를 함수의 인자로 올바르게 전달하는 코드는?',
    options: ['func(arr[5]);', 'func(&arr);', 'func(arr);', 'func(*arr);'],
    correctIndex: 2,
    explanation: '배열을 함수에 전달할 때는 배열 이름(arr)을 사용합니다. 배열 이름은 첫 번째 원소의 주소(&arr[0])를 의미합니다. arr[5]는 범위 초과 원소, &arr는 배열 포인터로 타입이 다르고, *arr는 arr[0]의 값입니다.',
  },
  {
    id: 'cl1-c7-q7',
    chapter: 7,
    question: '다음 선언에서 arr[3]의 값은?',
    codeBlock: 'int arr[5] = {10, 20, 30};',
    options: ['10', '20', '30', '0'],
    correctIndex: 3,
    explanation: 'arr[0]=10, arr[1]=20, arr[2]=30이고, 초기값이 지정되지 않은 arr[3]과 arr[4]는 자동으로 0으로 초기화됩니다.',
  },
  {
    id: 'cl1-c7-q8',
    chapter: 7,
    question: '다음 코드에서 printf의 출력 결과는? (double형 = 8바이트 가정)',
    codeBlock: 'double arr[6];\nprintf("%d %d\\n", (int)sizeof(arr), (int)(sizeof(arr) / sizeof(arr[0])));',
    options: ['40 5', '48 6', '24 3', '56 7'],
    correctIndex: 1,
    explanation: 'sizeof(double arr[6]) = 8 × 6 = 48바이트, sizeof(arr) / sizeof(arr[0]) = 48 / 8 = 6 (원소 개수)',
  },
  {
    id: 'cl1-c7-q9',
    chapter: 7,
    question: '다음 2차원 배열에서 data[1][2]의 값은?',
    codeBlock: 'int data[3][4] = {\n    {1, 2, 3, 4},\n    {5, 6, 7, 8},\n    {9, 10, 11, 12}\n};',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
    explanation: 'data[1]은 두 번째 행 {5, 6, 7, 8}이고, 인덱스 2는 세 번째 열(0부터 시작)이므로 data[1][2] = 7입니다.',
  },
  {
    id: 'cl1-c7-q10',
    chapter: 7,
    question: '다음 코드에서 printf의 출력 결과는?',
    codeBlock: 'int arr[3][3] = {{1, 2}, {3}};\nprintf("%d %d\\n", arr[0][2], arr[1][1]);',
    options: ['1 0', '0 0', '2 3', '0 1'],
    correctIndex: 1,
    explanation: 'arr[0]={1,2,0}, arr[1]={3,0,0}, arr[2]={0,0,0}으로 초기화됩니다. arr[0][2]=0, arr[1][1]=0이므로 "0 0"이 출력됩니다.',
  },
  {
    id: 'cl1-c7-q11',
    chapter: 7,
    question: '다음 코드에서 printf의 출력 결과는?',
    codeBlock: 'int arr[] = {3, 1, 4, 1, 5};\nint i, sum = 0;\nfor (i = 0; i < 5; i++)\n    sum += arr[i];\nprintf("%d\\n", sum);',
    options: ['10', '12', '14', '16'],
    correctIndex: 2,
    explanation: '3 + 1 + 4 + 1 + 5 = 14',
  },
  {
    id: 'cl1-c7-q12',
    chapter: 7,
    question: '다음 코드의 출력 결과는?',
    codeBlock: 'int arr[5] = {2, 4, 6, 8, 10};\nint i, max = arr[0];\nfor (i = 1; i < 5; i++) {\n    if (arr[i] > max)\n        max = arr[i];\n}\nprintf("%d\\n", max);',
    options: ['2', '8', '10', '6'],
    correctIndex: 2,
    explanation: 'max가 arr[0]=2에서 시작하여 4→6→8→10으로 갱신되므로 최종값은 10입니다.',
  },
  {
    id: 'cl1-c7-q13',
    chapter: 7,
    question: '다음 코드의 출력 결과는?',
    codeBlock: 'int i, j;\nint score[2][3] = {{90, 85, 70}, {60, 75, 80}};\nint sum = 0;\nfor (i = 0; i < 2; i++)\n    for (j = 0; j < 3; j++)\n        sum += score[i][j];\nprintf("%d\\n", sum / 6);',
    options: ['70', '76', '80', '85'],
    correctIndex: 1,
    explanation: '90+85+70+60+75+80 = 460, 460/6 = 76 (정수 나눗셈으로 소수점 절삭)',
  },
  {
    id: 'cl1-c7-q14',
    chapter: 7,
    question: '다음 코드의 출력 결과는?',
    codeBlock: 'void double_arr(int arr[], int size) {\n    int i;\n    for (i = 0; i < size; i++)\n        arr[i] *= 2;\n}\n\nint data[] = {1, 3, 5};\ndouble_arr(data, 3);\nprintf("%d %d %d\\n", data[0], data[1], data[2]);',
    options: ['1 3 5', '2 4 6', '2 6 10', '1 6 10'],
    correctIndex: 2,
    explanation: '배열은 주소(포인터)로 함수에 전달되므로, double_arr 내부에서 원소를 변경하면 원본 배열 data가 직접 수정됩니다. data[0]=1×2=2, data[1]=3×2=6, data[2]=5×2=10',
  },
  {
    id: 'cl1-c7-q15',
    chapter: 7,
    question: '다음 코드에서 발생하는 오류에 대한 설명으로 옳은 것은?',
    codeBlock: 'int arr[5];\nint i, sum = 0;\narr = {1, 2, 3, 4, 5};\nfor (i = 1; i <= 5; i++)\n    sum += arr[i];',
    options: [
      '선언 후 {}를 이용한 일괄 대입이 불가하며, 반복 인덱스가 arr[0]을 건너뛰고 arr[5]를 접근한다.',
      'sum을 0이 아닌 다른 값으로 초기화해야 한다.',
      '배열 크기를 10 이상으로 늘려야 한다.',
      'printf의 형식 지정자 %d가 잘못됐다.',
    ],
    correctIndex: 0,
    explanation: '오류 1: 배열 선언 이후 arr = {} 일괄 대입 불가 → 선언 시 초기화 필요. 오류 2: i=1로 시작하면 arr[0]이 누락되고, i=5일 때 arr[5]는 유효하지 않은 범위(out-of-bounds)입니다.',
  },
  {
    id: 'cl1-c7-q16',
    chapter: 7,
    question: '다음 코드에서 get_sum 호출의 오류와 올바른 수정 방법은?',
    codeBlock: 'int data[4] = {1, 2, 3, 4};\nprintf("합: %d\\n", get_sum(data[4], 4));',
    options: [
      'data[4]는 범위 초과 원소 값이므로 배열 이름 data를 전달해야 한다.',
      'data[4]는 배열의 마지막 원소이므로 올바르다.',
      '두 번째 인자 4를 5로 변경해야 한다.',
      'get_sum 함수의 반환 타입이 잘못됐다.',
    ],
    correctIndex: 0,
    explanation: 'data[4]는 int 값(범위 초과 접근)으로, 함수가 기대하는 int[](배열 주소)와 타입이 다릅니다. 배열 이름 data를 전달해야 합니다: get_sum(data, 4)',
  },
  {
    id: 'cl1-c7-q17',
    chapter: 7,
    question: '다음 코드가 최솟값 1을 출력하도록 for 루프의 빈칸에 들어갈 값으로 옳은 것은?',
    codeBlock: 'int arr[] = {5, 2, 8, 1, 9};\nint i, min = arr[0];\nfor (i = 1; i < ________; i++) {\n    if (arr[i] < min)\n        min = arr[i];\n}\nprintf("최솟값: %d\\n", min);',
    options: ['4', '5', '6', 'sizeof(arr)'],
    correctIndex: 1,
    explanation: 'arr은 원소 5개짜리 배열이므로 i < 5로 반복해야 인덱스 0~4를 모두 비교할 수 있습니다. i < 4이면 arr[4]=9를 확인하지 않아 최솟값이 틀려질 수 있습니다.',
  },
  {
    id: 'cl1-c7-q18',
    chapter: 7,
    question: '다음 코드가 각 행의 합계를 출력하도록 빈칸 ①과 ②에 들어갈 내용으로 옳은 것은?',
    codeBlock: 'int score[3][4] = {\n    {85, 90, 78, 92},\n    {70, 88, 95, 80},\n    {60, 75, 85, 90}\n};\nfor (i = 0; i < 3; i++) {\n    int sum = 0;\n    for (j = 0; j < ①; j++)\n        sum += ②;\n    printf("%d행 합계: %d\\n", i + 1, sum);\n}',
    options: [
      '① 4  /  ② score[i][j]',
      '① 3  /  ② score[i][j]',
      '① 4  /  ② score[j][i]',
      '① 5  /  ② score[i][j]',
    ],
    correctIndex: 0,
    explanation: '각 행에는 4개의 점수가 있으므로 j < 4, 각 원소는 score[i][j]로 접근합니다. 1행: 345, 2행: 333, 3행: 310',
  },
]

// ──────────────────────────────────────────
// Chapter 8  — 포인터 (Pointer)
// ──────────────────────────────────────────
const chapter8: QuizQuestion[] = [
  {
    id: 'cl1-c8-q1',
    chapter: 8,
    question: '다음 중 포인터(pointer)에 대한 설명으로 옳지 않은 것은?',
    options: [
      '포인터 변수에는 메모리의 주소가 저장된다.',
      'int*형 포인터와 double*형 포인터의 크기는 같은 플랫폼에서 항상 동일하다.',
      'NULL은 메모리 0번지 주소를 의미한다.',
      '포인터를 역참조하면 포인터가 가리키는 변수에 접근할 수 있다.',
    ],
    correctIndex: 2,
    explanation: 'NULL은 메모리 0번지가 아닙니다. NULL은 포인터가 어떤 변수도 가리키지 않는다는 의미의 매크로 상수(0으로 정의됨)이며, 실제 메모리 0번지와는 개념적으로 다릅니다.',
  },
  {
    id: 'cl1-c8-q2',
    chapter: 8,
    question: '다음 선언이 있을 때, & 연산자를 올바르게 사용한 코드는?',
    codeBlock: 'int a = 5;',
    options: [
      'int *p = &5;',
      'int *p = &(a + 1);',
      'int *p = &a;',
      'printf("%p", &(a * 2));',
    ],
    correctIndex: 2,
    explanation: '& 연산자는 반드시 변수와 함께 사용해야 합니다. 리터럴 상수(&5)나 수식(&(a+1), &(a*2))의 주소는 구할 수 없습니다.',
  },
  {
    id: 'cl1-c8-q3',
    chapter: 8,
    question: '다음 중 널 포인터(NULL pointer)에 대한 설명으로 옳지 않은 것은?',
    options: [
      '포인터가 어떤 변수도 가리키지 않음을 나타낸다.',
      'NULL로 초기화된 포인터를 역참조하면 프로그램이 비정상 종료될 수 있다.',
      'NULL 대신 숫자 0을 포인터의 초기값으로 사용할 수 있다.',
      'NULL은 메모리 0번지 주소를 의미한다.',
    ],
    correctIndex: 3,
    explanation: 'NULL은 메모리 0번지 주소가 아니라 포인터가 아무것도 가리키지 않는다는 의미입니다. NULL 대신 숫자 0을 사용하는 것은 표준 C에서 허용됩니다.',
  },
  {
    id: 'cl1-c8-q4',
    chapter: 8,
    question: '다음 선언에서 허용되는 연산으로 옳은 것은?',
    codeBlock: 'int a = 10, b = 20;\nconst int *p = &a;',
    options: [
      '*p = 99;',
      'p = &b;',
      '(*p)++;',
      'p++는 컴파일 에러가 된다.',
    ],
    correctIndex: 1,
    explanation: 'const int *p는 읽기 전용 포인터입니다. 포인터가 가리키는 값(*p) 변경은 불가하지만, 포인터 자체(p)는 다른 변수를 가리키도록 변경할 수 있습니다. ①③은 값 변경 시도이므로 컴파일 에러, ④의 p++는 실제로 허용됩니다.',
  },
  {
    id: 'cl1-c8-q5',
    chapter: 8,
    question: '다음 코드에서 *(p + 2)의 값으로 옳은 것은?',
    codeBlock: 'int arr[] = {10, 20, 30, 40, 50};\nint *p = arr;',
    options: ['12', '20', '30', '40'],
    correctIndex: 2,
    explanation: 'p는 arr[0]을 가리킵니다. 포인터 + 정수 N은 N개 원소만큼 앞으로 이동합니다. p + 2는 arr[2]의 주소이므로 *(p + 2) = arr[2] = 30입니다.',
  },
  {
    id: 'cl1-c8-q6',
    chapter: 8,
    question: '두 변수의 값을 실제로 교환하는 swap 함수의 올바른 매개변수 선언은?',
    codeBlock: 'void swap(________)\n{\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}',
    options: [
      'int a, int b',
      'int *a, int *b',
      'int a, int *b',
      'const int *a, const int *b',
    ],
    correctIndex: 1,
    explanation: '원본 변수를 직접 변경하려면 참조에 의한 호출(call by reference)이 필요합니다. C에서는 포인터를 매개변수로 선언(int *a, int *b)하고 호출 시 주소(&x, &y)를 전달합니다.',
  },
  {
    id: 'cl1-c8-q7',
    chapter: 8,
    question: '다음 코드의 출력 결과는? (첫 번째 줄, 두 번째 줄 순서대로)',
    codeBlock: 'int a = 42;\nint *p = &a;\nprintf("%d\\n", *p);\n*p = 100;\nprintf("%d\\n", a);',
    options: ['42, 42', '42, 100', '100, 100', '100, 42'],
    correctIndex: 1,
    explanation: '*p는 포인터 p가 가리키는 변수 a의 값입니다. *p = 100은 a = 100과 동일하게 원본 변수를 직접 변경합니다. 따라서 42, 100 순으로 출력됩니다.',
  },
  {
    id: 'cl1-c8-q8',
    chapter: 8,
    question: '다음 코드의 출력 결과는? (32비트 플랫폼 가정)',
    codeBlock: 'int a = 0;\ndouble b = 0.0;\nint *p1 = &a;\ndouble *p2 = &b;\nprintf("%d %d\\n", (int)sizeof(p1), (int)sizeof(p2));',
    options: ['4 8', '4 4', '8 8', '2 4'],
    correctIndex: 1,
    explanation: '포인터의 크기는 가리키는 데이터형에 관계없이 같은 플랫폼에서 항상 동일합니다. 32비트 플랫폼에서는 int*, double* 모두 4바이트입니다.',
  },
  {
    id: 'cl1-c8-q9',
    chapter: 8,
    question: '다음 코드에서 printf의 출력 결과는?',
    codeBlock: 'int x = 5, y = 10;\nint *p = &x;\n*p = *p + y;\np = &y;\n*p *= 2;\nprintf("%d %d\\n", x, y);',
    options: ['5 20', '15 10', '15 20', '5 10'],
    correctIndex: 2,
    explanation: '①p=&x, *p=5+10=15 → x=15 ②p=&y, *p*=2 → y=10×2=20 따라서 x=15, y=20이 출력됩니다.',
  },
  {
    id: 'cl1-c8-q10',
    chapter: 8,
    question: '다음 코드에서 *(p + 3)의 값은?',
    codeBlock: 'int arr[] = {1, 3, 5, 7, 9};\nint *p = arr;',
    options: ['5', '7', '9', '3'],
    correctIndex: 1,
    explanation: 'p는 arr[0]을 가리킵니다. *(p + 3) = arr[3] = 7입니다.',
  },
  {
    id: 'cl1-c8-q11',
    chapter: 8,
    question: '다음 코드의 출력 결과는?',
    codeBlock: 'void change(int x)\n{\n    x = 999;\n}\n\nint n = 10;\nchange(n);\nprintf("%d\\n", n);',
    options: ['999', '10', '0', '컴파일 에러'],
    correctIndex: 1,
    explanation: 'change 함수의 매개변수 x는 n의 복사본입니다. 함수 내부에서 x = 999로 변경해도 원본 n에는 영향이 없습니다. 이것이 값에 의한 호출(call by value)의 핵심입니다.',
  },
  {
    id: 'cl1-c8-q12',
    chapter: 8,
    question: '다음 코드의 출력 결과는?',
    codeBlock: 'void swap(int *a, int *b)\n{\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}\n\nint x = 3, y = 7;\nswap(&x, &y);\nprintf("%d %d\\n", x, y);',
    options: ['3 7', '7 3', '0 0', '3 3'],
    correctIndex: 1,
    explanation: 'swap(&x, &y)로 x와 y의 주소를 전달하므로, 함수 안에서 역참조(*a, *b)를 통해 원본 변수를 직접 수정합니다. 따라서 x와 y의 값이 실제로 교환되어 "7 3"이 출력됩니다.',
  },
  {
    id: 'cl1-c8-q13',
    chapter: 8,
    question: '다음 코드의 출력 결과는? (세 줄 순서대로)',
    codeBlock: 'int arr[] = {10, 20, 30, 40, 50};\nint *p = arr;\nprintf("%d\\n", *(p + 1));\nprintf("%d\\n", p[3]);\np++;\nprintf("%d\\n", *p);',
    options: ['20 → 40 → 30', '20 → 40 → 20', '10 → 30 → 20', '20 → 30 → 30'],
    correctIndex: 1,
    explanation: '*(p+1)=arr[1]=20, p[3]=arr[3]=40 (이 시점 p는 아직 arr[0] 가리킴), p++로 p가 arr[1]을 가리킨 후 *p=arr[1]=20. 따라서 20 → 40 → 20 순으로 출력됩니다.',
  },
  {
    id: 'cl1-c8-q14',
    chapter: 8,
    question: '다음 코드의 출력 결과는? (세 줄 순서대로)',
    codeBlock: 'int arr[] = {1, 2, 3, 4, 5};\nint *p = arr + 2;\nprintf("%d\\n", *p);\nprintf("%d\\n", *(p - 1));\nprintf("%d\\n", p[1]);',
    options: ['3 → 2 → 4', '2 → 1 → 3', '3 → 1 → 4', '1 → 2 → 3'],
    correctIndex: 0,
    explanation: 'p = arr + 2이므로 p는 arr[2]를 가리킵니다. *p=arr[2]=3, *(p-1)=arr[1]=2, p[1]=*(p+1)=arr[3]=4. 따라서 3 → 2 → 4 순으로 출력됩니다.',
  },
  {
    id: 'cl1-c8-q15',
    chapter: 8,
    question: '다음 코드의 오류와 올바른 수정 방법으로 옳은 것은?',
    codeBlock: 'int a = 5;\nint *p;\np = a;\nprintf("%d\\n", *p);\np = NULL;\nprintf("%d\\n", *p);',
    options: [
      'p = a를 p = &a로, NULL 포인터 역참조를 제거해야 한다.',
      'int *p를 int p로 바꿔야 한다.',
      '*p 대신 p를 직접 printf에 넣어야 한다.',
      'printf 형식 지정자를 %p로 변경해야 한다.',
    ],
    correctIndex: 0,
    explanation: '오류 1: p = a는 int 값을 포인터에 대입 → p = &a (주소 대입)로 수정. 오류 2: p = NULL 이후 *p 역참조는 세그멘테이션 오류(비정상 종료) 발생 → 해당 코드 제거 또는 NULL 체크 후 접근.',
  },
  {
    id: 'cl1-c8-q16',
    chapter: 8,
    question: '다음은 score에 10을 더하는 프로그램이다. 오류와 수정 방법으로 옳은 것은?',
    codeBlock: 'void add_ten(int n)\n{\n    n += 10;\n}\n\nint score = 80;\nadd_ten(score);\nprintf("%d\\n", score);',
    options: [
      '매개변수를 int *n으로, 함수 내부를 *n += 10으로, 호출을 add_ten(&score)로 수정한다.',
      'n += 10을 return n + 10으로 변경한다.',
      'void를 int로 바꾸고 return n을 추가한다.',
      'score를 전역 변수로 선언한다.',
    ],
    correctIndex: 0,
    explanation: '값에 의한 호출(call by value)이므로 n은 score의 복사본입니다. 원본을 수정하려면 포인터 매개변수(int *n)를 사용하고 역참조(*n += 10)하며, 주소(&score)를 전달해야 합니다.',
  },
  {
    id: 'cl1-c8-q17',
    chapter: 8,
    question: '다음 swap 함수가 "20 10"을 출력하도록 빈칸 ①~④에 들어갈 내용으로 옳은 것은?',
    codeBlock: 'void swap(①, ②)\n{\n    int tmp = *a;\n    *a = *b;\n    *b = tmp;\n}\n\nint x = 10, y = 20;\nswap(③, ④);\nprintf("%d %d\\n", x, y);',
    options: [
      '① int *a  ② int *b  ③ &x  ④ &y',
      '① int a   ② int b   ③ x   ④ y',
      '① int *a  ② int *b  ③ x   ④ y',
      '① int a   ② int b   ③ &x  ④ &y',
    ],
    correctIndex: 0,
    explanation: '포인터 매개변수 int *a, int *b로 선언하고, 호출 시 변수의 주소 &x, &y를 전달해야 역참조(*a, *b)로 원본 값을 교환할 수 있습니다.',
  },
  {
    id: 'cl1-c8-q18',
    chapter: 8,
    question: '다음 코드가 "합계: 15"를 출력하도록 빈칸 ①과 ②에 들어갈 내용으로 옳은 것은?',
    codeBlock: 'int arr[] = {1, 2, 3, 4, 5};\nint *p = ①;\nint i, sum = 0;\nfor (i = 0; i < 5; i++) {\n    sum += ②;\n    p++;\n}\nprintf("합계: %d\\n", sum);',
    options: [
      '① arr  /  ② *p',
      '① &arr[1]  /  ② *p',
      '① arr  /  ② p[0]',
      '① &arr[4]  /  ② *p',
    ],
    correctIndex: 0,
    explanation: 'p = arr로 첫 번째 원소를 가리키고, *p로 현재 가리키는 값을 읽습니다. p++로 다음 원소로 이동하면서 1+2+3+4+5=15를 합산합니다.',
  },
]

// ──────────────────────────────────────────
// Chapter 9  (추가 예정)
// ──────────────────────────────────────────
const chapter9: QuizQuestion[] = []

export const questions: QuizQuestion[] = [
  ...chapter1to6,
  ...chapter7,
  ...chapter8,
  ...chapter9,
]
